### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by N3rdP1um23** [N3rdP1um23/laravel-friendships#1]
Hey! @demency do you have any plans to support this package again?

**Comment by Zen0x7** [comment]
Hi @N3rdP1um23.

Not by the moment. I'm a little bit scared of code usage, specially when is used for bad purposes. Maybe I'll remade or rewrite the package to release it using another license, ofc, more strict only for good purposes.

**Comment by N3rdP1um23** [comment]
Hello @demency! No worries at all and I totally understand. The only reason I ask was since I was actively using it in a project and it broke a few things. 

If you'd like, I can make this a private repository for myself and remove it if and when you release a new version.

Just let me know! :)

**Comment by Zen0x7** [comment]
I think your copied repository is a good idea. Good luck ✌️

**Comment by N3rdP1um23** [comment]
Sounds good and thanks again for the initial work on the repository 🙂 Hopefully I can support it going forward.
